[tool.poetry]
name = "nifi-receipt"
version = "0.1.0"
description = ""
authors = ["Sam Bryant <srbry@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
blaise-dds = {git = "https://github.com/ONSdigital/blaise-data-delivery-status-client.git", rev = "main"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
behave = "^1.2.6"
isort = "^5.8.0"
black = "^20.8b1"
mypy = "^0.812"
flake8 = "^3.9.0"
flake8-cognitive-complexity = "^0.1.0"
requests-mock = "^1.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
